Add listings app, except for images on the Listing model.
Sam-Macpherson/sublet-shark pull request #1
Opened 2020-11-27 02:13 UTC by Sam-Macpherson

2020-11-27 02:15 UTC, Sam-Macpherson commented
Like a silly boy I forgot to add __pycache__ to the gitignore initally, so this change also removes those from the repo.

2020-11-27 03:00 UTC, LzPwns requested changes
I think we have to blow up the whole repository.

2020-11-27 03:35 UTC, Sam-Macpherson commented on listings/models/listing.py
> +        output += f'({self.id}) {str(self.start_date)} to ' \
Alright for now I can remove the ID field and if we ever need it down the line we can re-add it or something.

2020-11-27 03:36 UTC, Sam-Macpherson commented on listings/models/listing.py
> +    address = CharField(
Definitely something we'll make in the future.

2020-11-27 03:36 UTC, Sam-Macpherson commented on listings/models/listing.py
> +
Sure I'll add that ordering, I think start_date is proably the most apt.

2020-11-27 03:36 UTC, Sam-Macpherson commented on subletshark/settings.py
> +    'listings.apps.ListingsConfig',
Didn't know that, will change. The base app does not need to be added.

2020-11-27 03:41 UTC, Sam-Macpherson commented on listings/models/listing.py
> +    address = CharField(
I think i'll add it as a property though, so we'll use it like `listing.term_length`

2020-11-28 23:09 UTC, LzPwns requested changes
I think you're gonna wanna update the tests once you change the term length calculation. Tests for 0 months, tests where the start date needs to be rounded (right now it's mostly using January 1st)

2020-11-28 23:09 UTC, LzPwns commented on listings/models/room.py
> +                 f'for listing: {self.listing_id} '
still a massive `__str__` but I'll let it slide because of those checkmarks

2020-11-28 23:09 UTC, LzPwns commented on listings/tests.py
> +            # May 15 - June 6, 1 month
nice

2020-11-28 23:09 UTC, LzPwns commented on listings/tests.py
> +            self.listing.save()
I think you can just do `self.listing.update(start_date=start_date, end_date=end_date)`

2020-11-29 00:46 UTC, Sam-Macpherson commented on listings/models/listing.py
> +                                    'one month.'))
I think you do not have to because no matter what the validation errors will get raised by super().clean() or not and then in line 63 and 66 as well, or not. Either way the necessary ValidationErrors are being raised here, but I will change it to make it more consistent with the django docs.

2020-11-29 00:46 UTC, Sam-Macpherson commented on listings/models/room.py
> +                 f'for listing: {self.listing_id} '
I haven't changed it since the last PR.

2020-11-29 00:51 UTC, Sam-Macpherson commented on listings/tests.py
> +            self.listing.save()
I was pretty sure that .update doesn't call the clean method and save does, but now that I've looked into it, it turns out that neither does .save(), so the clean I wrote was useless. I'll override the save() method to actually call our custom clean() method, and leave this as save() here, but I'll add the update_fields parameter.

2020-11-29 02:15 UTC, Sam-Macpherson commented
Ignore the failing CI tests for now, I think they're failing because I need to set up postgres to run within them. The tests pass locally.

2020-11-29 06:36 UTC, LzPwns reviewed
you're almost there champ

2020-11-29 06:36 UTC, LzPwns commented on listings/models/listing.py
> +        number_of_months = day_difference / 30.4375
should have this number in a constants file

2020-11-29 06:36 UTC, LzPwns commented on listings/models/listing.py
> +        return (date + timedelta(days=16)).replace(day=1)
do we still need this method?

2020-11-29 06:36 UTC, LzPwns commented on listings/models/listing.py
> +        return int(number_of_months + 0.5)
even though this is a neat strat, you could just `round()`

2020-11-29 14:44 UTC, Sam-Macpherson commented on listings/models/listing.py
> +        number_of_months = day_difference / 30.4375
True.

2020-11-29 14:45 UTC, Sam-Macpherson commented on listings/models/listing.py
> +        return (date + timedelta(days=16)).replace(day=1)
I want to keep this method in because without it we'd be doing a calculation twice in 1 place, back to back, and this way we can make use of a docstring instead of comments to explain it.

2020-11-29 14:45 UTC, Sam-Macpherson commented on listings/models/listing.py
> +        return int(number_of_months + 0.5)
Lol yeah I guess I got too excited.

2020-11-29 15:05 UTC, Sam-Macpherson commented on listings/models/listing.py
> +        return (date + timedelta(days=16)).replace(day=1)
Also, in the next patch I'm adding that thing we talked about, "instead of using 16 we use half the # of days in the month in question", so that calculation will also take place here.

2020-11-30 16:31 UTC, LzPwns approved these changes

2020-11-30 17:54 UTC, merged